### ISSUE TITLE
Fields are not added

### ISSUE THREAD

**Issue by Ardiea** [Ardiea/fileagebeat#1]
```
      fileagebeat:
        fields:
          lob: "lob"
          product: "product"
          role: "mda"
          tier: "production"

        inputs:
        - name: "testname"
          paths:
          - 'filepathshere'
          heartbeat: false
          period: 60s
          threshold: 5m
          max_depth: 1
```
